### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by DuncanEll2** [ixhal/ixhal-weight#2]
Hey like the script and the concept of it but does not seem to work for me, i am using qbcore with ox_inventory , i do get an error on line 30 (        for k, v in pairs(items) do weight += v.weight * v.amount end     ) stating nil value v.amount

**Comment by ixhal** [comment]
Make sure you are using the latest version! This should be fixed now, If not you are probably running a old version of ox_inventory and should update!
